version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Enable polling for hot reload in Docker
      - NEXT_WEBPACK_USEPOLLING=1
    # Uncomment and modify when backend is ready
    # depends_on:
    #   - backend

  # Uncomment and customize this section when you decide on your backend tech stack
  # backend:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development 