version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile  # Uses the production Dockerfile by default
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Uncomment when backend is ready
    # depends_on:
    #   - backend

  # Uncomment and customize when you decide on backend
  # backend:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production 